In [9]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option('display.float_format', lambda x: f'{x:,.0f}')
df = pd.read_csv('ForeignGifts_edu.csv',low_memory=False)
df.head()

,ID,OPEID,Institution Name,City,State,Foreign Gift Received Date,Foreign Gift Amount,Gift Type,Country of Giftor,Giftor Name
0,1,102000,Jacksonville State University,Jacksonville,AL,43738,250000,Monetary Gift,CHINA,NaN
1,2,104700,Troy University,Troy,AL,43592,463657,Contract,CHINA,Confucius Institute Headquarters
2,3,105100,University of Alabama,Tuscaloosa,AL,43466,3649107,Contract,ENGLAND,Springer Nature Customer Service Ce
3,4,105100,University of Alabama,Tuscaloosa,AL,43472,1000,Contract,SAUDI ARABIA,Saudi Arabia Education Mission
4,5,105100,University of Alabama,Tuscaloosa,AL,43479,49476,Contract,SAUDI ARABIA,Saudi Arabia Education Mission

In [ ]:
#Question 1.2
'''The three gift types are contracts, monetary gifts, and real estate. Contract and monetary gifts are the most common, with contract being the
most, and the average gift amounts for both are around the same. Real estate is much less common, only 11 gifts, but has a much higher average
value, though with so few gifts that number is not very reliable.'''

display(df['Gift Type'].unique())
display(df['Gift Type'].value_counts())
df.groupby('Gift Type')['Foreign Gift Amount'].describe()

<ArrowStringArray>
['Monetary Gift', 'Contract', 'Real Estate']
Length: 3, dtype: str

Gift Type
Contract         17274
Monetary Gift    10936
Real Estate         11
Name: count, dtype: int64

,count,mean,std,min,25%,50%,75%,max
Gift Type,,,,,,,,
Contract,"17,274","625,795","3,768,217","-537,770","13,758","110,000","366,000","99,999,999"
Monetary Gift,"10,936","528,150","2,086,487",1,250,"50,000","400,000","48,842,186"
Real Estate,11,"1,335,265","1,412,071","39,456","370,574","667,555","2,121,736","4,312,000"

In [ ]:
#Question 1.3.1
#Qatar gives the most money

df.groupby('Country of Giftor')['Foreign Gift Amount'].sum().sort_values(ascending=False)

Country of Giftor
QATAR           2706240869
ENGLAND         1464906771
CHINA           1237952112
SAUDI ARABIA    1065205930
BERMUDA          899593972
                   ...
IRAN                    80
ST. LUCIA               50
CROATIA                 26
SLOVAKIA                20
ERITREA                  3
Name: Foreign Gift Amount, Length: 155, dtype: int64

In [ ]:
#Question 1.3.2
#England recieves the most number of gifts

df.groupby('Country of Giftor')['Foreign Gift Amount'].count().sort_values(ascending=False)

Country of Giftor
ENGLAND            3655
CHINA              2461
CANADA             2344
JAPAN              1896
SWITZERLAND        1676
                   ...
ST. LUCIA             1
TOKELAU               1
SLOVAKIA              1
ST. KITTS-NEVIS       1
TUNISIA               1
Name: Foreign Gift Amount, Length: 155, dtype: int64

In [ ]:
#Question 1.3.3
#Bermuda has the highest mean gift amount while Antigua has the highest meadian.

display(df.groupby('Country of Giftor')['Foreign Gift Amount'].mean().sort_values(ascending=False))
df.groupby('Country of Giftor')['Foreign Gift Amount'].median().sort_values(ascending=False)

Country of Giftor
BERMUDA     7,688,837
ECUADOR     3,985,140
QATAR       3,905,109
ANTIGUA     3,435,545
JERSEY      3,064,589
               ...
ST. LUCIA          50
IRAN               40
CROATIA            26
SLOVAKIA           20
ERITREA             3
Name: Foreign Gift Amount, Length: 155, dtype: float64

Country of Giftor
ANTIGUA                    3,435,545
ISLE OF MAN                2,000,000
VIRGIN ISLANDS (BRITISH)   1,429,333
CYPRUS                     1,250,000
MARSHAL ISLANDS (THE)      1,041,666
                              ...
ST. LUCIA                         50
IRAN                              40
CROATIA                           26
SLOVAKIA                          20
ERITREA                            3
Name: Foreign Gift Amount, Length: 155, dtype: float64

In [ ]:
#Question 1.3.4
#Carnegie Mellon University recieved the most amount of money.

df.groupby('Institution Name')['Foreign Gift Amount'].sum().sort_values(ascending=False)

Institution Name
Carnegie Mellon University               1477922504
Cornell University                       1289937761
Harvard University                        954803610
Massachusetts Institute of Technology     859071692
Yale University                           613441311
                                            ...
Jacksonville State University                250000
Metropolitan State University                235439
University of California, Merced             182514
University of Central Oklahoma               160288
University of Jamestown                         500
Name: Foreign Gift Amount, Length: 318, dtype: int64

In [ ]:
#Question 1.3.5
#University of California recieved the most number of gifts.

df.groupby('Institution Name')['Foreign Gift Amount'].count().sort_values(ascending=False)

Institution Name
University of California, Los Angeles          3916
California Institute of Technology             2502
Columbia University in the City of New York    1127
Ohio State University (The)                    1014
Johns Hopkins University                        899
                                               ...
Washington Adventist University                   1
Western Oregon University                         1
Wesleyan College                                  1
Wayne State University                            1
Yeshiva University                                1
Name: Foreign Gift Amount, Length: 318, dtype: int64

In [24]:
#Question 1.3.6
#The mean gift amount is ~$590K while the median is ~$95K. and difference is due to a few very large gifts skewing the mean.

display(round(df['Foreign Gift Amount'].mean()))
round(df['Foreign Gift Amount'].median())

588233

94615

In [ ]:
#Question 1.3.7
#The largest flow from county to institution is from Qatar to Cornell.

df.groupby(['Country of Giftor', 'Institution Name'])['Foreign Gift Amount'].sum().sort_values(ascending=False)

Country of Giftor     Institution Name
QATAR                 Cornell University                       1018473315
BERMUDA               Carnegie Mellon University                750000000
QATAR                 Texas A&M University                      504099350
                      Carnegie Mellon University                425410702
                      Georgetown University                     327128310
                                                                  ...
CAYMAN ISLANDS (THE)  Johns Hopkins University                         10
TRINIDAD              Westminster Theological Seminary                 10
GERMANY               Westminster Theological Seminary                 10
ERITREA               University of California, Los Angeles             3
MEXICO                University of California, Merced                  1
Name: Foreign Gift Amount, Length: 2685, dtype: int64

In [ ]:
#Question 1.3.8
#The largest indivdual gifter is the Qatar Foundation.

df.groupby('Giftor Name')['Foreign Gift Amount'].sum().sort_values(ascending=False)

Giftor Name
Qatar Foundation                       1166503744
Qatar Foundation/Qatar National Res     796197000
Qatar Foundation for Education          373945215
Anonymous                               338793629
Saudi Arabian Cultural Mission          275221475
                                          ...
Noh, Jongyoun                                   1
Zhang, Stephanie                                1
VISETSUTH, PEERANUT                             1
Francois, Pierre                                1
Cox, Melati                                     1
Name: Foreign Gift Amount, Length: 8993, dtype: int64